image: node:12.13.0

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm install # npm install
    - npm run build # npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - master
