name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [16.6.1]
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      #- run: npm run build 
      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@v2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: anchuanyuan//anchuanyuan.github.io.git
          TARGET_BRANCH: master
          BUILD_SCRIPT:  npm run build
          BUILD_DIR: docs/.vuepress/dist/
          COMMIT_MESSAGE: Auto deploy by the Vuepress-deploy
